ViewModels/ArtistListViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using RiyadhVoice.Model;

namespace RiyadhVoice.ViewModels
{
    public class ArtistListViewModel
    {
        public IEnumerable<ArtistManagement> Artists { get; set; }

    }
}

ViewModels/EventCartViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using RiyadhVoice.Model;

namespace RiyadhVoice.ViewModels
{
    public class EventCartViewModel
    {
        public AvailedEvents AvailedEvents  { get; set; }
    }
}

ViewModels/EventsListViewModel.cs
using RiyadhVoice.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace RiyadhVoice.ViewModels
{
    public class EventsListViewModel

    {
        public string CurrentCategory { get; set; }
        public IEnumerable<Events> Events { get; set; }

    }
}

ViewModels/homeViewModel.cs
using RiyadhVoice.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace RiyadhVoice.ViewModels
{
    public class homeViewModel
    {
        public IEnumerable<Events> Eventsoftheweek { get; set; }

    }
}

Controllers/ArtistsController.cs
using Microsoft.AspNetCore.Mvc;
using RiyadhVoice.Model;
using RiyadhVoice.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace RiyadhVoice.Controllers
{
    public class ArtistsController : Controller
    {
        
            private readonly IArtistRepository _artistRepository;
            private readonly ICategoryRepository _CategoryRepository;

            public ArtistsController(IArtistRepository artistRepository, ICategoryRepository categoryRepository)
            {
                _artistRepository = artistRepository;
                _CategoryRepository = categoryRepository;
            }
            public ViewResult List()
            {
                ArtistListViewModel artistListViewModel = new ArtistListViewModel();
                artistListViewModel.Artists = _artistRepository.AllArtists;

                // eventsListViewModel.CurrentCategory = "Wedding";
                return View(artistListViewModel);
            }

            public IActionResult Details(int id)
            {
                var Artists = _artistRepository.GetArtist(id);
                if (Artists == null)
                    return NotFound();

                return View(Artists);
            }
        }
    }

Controllers/ContactController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace RiyadhVoice.Controllers
{
    public class ContactController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Controllers/EventCartController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using RiyadhVoice.ViewModels;
using RiyadhVoice.Model;



namespace RiyadhVoice.Controllers
{
    public class EventCartController : Controller
    {
        private readonly IEventsRepository _EventsRepository;
        private readonly ICategoryRepository _CategoryRepository;
        private readonly AvailedEvents _availedEvents;

        public EventCartController(IEventsRepository EventsRepository, AvailedEvents availedEvents)
        {
            _availedEvents = availedEvents;

            _EventsRepository = EventsRepository;
        }

        //public ViewResult Index()
        //{
        //    var eventCartViewModel = new EventCartViewModel
        //    {
        //        AvailedEvents = _availedEvents,

        //    }

        //   return  View();
        //}

        public RedirectToActionResult AddToShoppingCart(int EventID)
        {
            var selectedPie = _EventsRepository.AllEvents.FirstOrDefault(p => p.Eventid == EventID);

            if (selectedPie != null)
            {
                _availedEvents.AddToCart(selectedPie, 1);
            }
            return RedirectToAction("Index");
        }

        public RedirectToActionResult RemoveFromShoppingCart(int EventID)
        {
            var selectedPie = _EventsRepository.AllEvents.FirstOrDefault(p => p.Eventid == EventID);

            if (selectedPie != null)
            {
                _availedEvents.RemoveFromCart(selectedPie);
            }
            return RedirectToAction("Index");
        }
        public IActionResult Index()
        {
            return View();
        }


    }
}

Controllers/EventsController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using RiyadhVoice.Model;
using RiyadhVoice.ViewModels;

namespace RiyadhVoice.Controllers
{
    public class EventsController : Controller
    {
        private readonly IEventsRepository _EventsRepository;
        private readonly ICategoryRepository _CategoryRepository;

        public EventsController (IEventsRepository eventsRepository , ICategoryRepository categoryRepository)
        {
            _EventsRepository = eventsRepository;
            _CategoryRepository = categoryRepository;
        }
        public ViewResult List()
        {
            EventsListViewModel eventsListViewModel = new EventsListViewModel();
            eventsListViewModel.Events = _EventsRepository.AllEvents;

           // eventsListViewModel.CurrentCategory = "Wedding";
            return View(eventsListViewModel);
        }

        public IActionResult Details(int id)
        {
            var events = _EventsRepository.GetEventByID(id);
            if ( events == null)
                return NotFound();

            return View(events);
        }

    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using RiyadhVoice.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using RiyadhVoice.ViewModels;

namespace RiyadhVoice.Controllers
{
    public class HomeController : Controller
    {
        private readonly IEventsRepository _EventsRepository;

        public HomeController (IEventsRepository eventsRepository)
        {
            _EventsRepository = eventsRepository;
        }


        public IActionResult Index()
        {

            var homeViewModel = new homeViewModel
            {
                Eventsoftheweek = _EventsRepository.EventOfTheWeek
            };
            return View(homeViewModel);
        }
    }
}

Controllers/VisionController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace RiyadhVoice.Controllers
{
    public class VisionController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace RiyadhVoice.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace RiyadhVoice.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace RiyadhVoice.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RiyadhVoice</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">RiyadhVoice</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - RiyadhVoice - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

Views/Artists/Details.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@model ArtistManagement

<h2>@Model.A_Name</h2>

<div class="thumbnail">
    <img alt="@Model.A_Name" src="@Model.A_ImageURL">
    <div class="caption-full">
        <h3>
            <a href="#">@Model.A_Name</a>
        </h3>
        <h4 style="color:black">@Model.A_ShortDescription</h4>
        <p style="color: black">@Model.A_LongDescription</p>
    </div>

</div>

Views/Artists/List.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@model ArtistListViewModel


@foreach (var artists in Model.Artists)
{ 

    <partial name="_ArtistCard" model="artists" />
}

Views/Contact/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<h3 style="color:white;font-size:large;">
    Please contact us by sending an email using the button below
    
</h3>

<email address="s.hisham13@gmail.com" content="Contact us"></email>

Views/EventCart/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@model EventCartViewModel

<h2>Your Availed Events</h2>
<h4>We value your choice! Here are your availed services, we will get in touch with you soon!</h4>
<table class="table table-bordered table-striped">
    <thead>
        <tr>
            <th>Selected amount</th>
            <th>Events</th>
            <th class="text-right">Price</th>
            <th class="text-right">Subtotal</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var line in Model.AvailedEvents.AvailedEventItems)
        {
            <tr>
                <td class="text-center">@line.Amount</td>
                <td class="text-left">@line.Events.Name</td>
                
            </tr>
        }
    </tbody>
    <tfoot>
        
    </tfoot>
</table>

Views/Events/Details.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@model Events

<h2>@Model.Name</h2>

<div class="thumbnail">
    <img alt="@Model.Name" src="@Model.ImageURL">
    <div class="caption-full">
        <h3>
            <a href="#">@Model.Name</a>
        </h3>
        <h4 style="color:black">@Model.ShortDescription</h4>
        <p style="color: black">@Model.LongDescription</p>
    </div>
   
</div>

Views/Events/List.cshtml
@model EventsListViewModel


    <h1>@Model.CurrentCategory</h1>
    @foreach (var events in Model.Events)
        {
         <partial name="_EventCard" model="events" />
        }


  

Views/Home/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@model homeViewModel

<div class="welcomeText">
    <h1>Let's enlight the glory of your events with music,</h1>
    <h2>the language of spirit!</h2>
</div>

<div><br /></div>
<div><br /></div>
<div><br /></div>
<div><br /></div>
<div><br /></div>
<div><br /></div>
<div><br /></div>
<div><br /></div>

<partial name="_Carousel" />


<div class="welcomeText">
    <h3>"Why choose us!"</h3>
    <p>
        It’s our attention to the small stuff, scheduling of timelines and keen event management that makes us stand out from the rest. We are creative,
        while keeping a close eye on the calendar and your budget.
    </p>
    <p> Morever, We deeply understand and go with the famous saying - </p>
    <h4>
        <br />
        <br />
        Music is the moonlight in the gloomy night of life.
    </h4>
    <h5 style="font-family:'Bookman Old Style';font-size:large;font-style:italic;position:relative;left:400px;">
        -John Paul Friedrich Richter
    </h5>

</div>

<div><br /></div>
<div><br /></div>
<div><br /></div>
<div><br /></div>
<div><br /></div>
<div><br /></div>
<div><br /></div>
<div><br /></div>
<div><br /></div>
<div><br /></div>
<div><br /></div>
<div><br /></div>
<div><br /></div>
<div><br /></div>
<div><br /></div>
<div><br /></div>
<div><br /></div>
<div><br /></div>



<div class="ArtistSlide">
    <h2 class="myxx">Artist and Event of the week</h2>
    <h4 class="caption1">Our Monthly achievment - just for you!</h4>
</div>
    <div><br /></div>
    <div><br /></div>

    <partial name="_Carousel2" />


    @*<div class="row">

            @foreach (var events in Model.Eventsoftheweek)
            {
                <partial name="_EventCard" model="events" />
            }

        </div>*@

Views/Shared/_ArtistCard.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@model ArtistManagement

<div class="col-sm-4 col-lg-    4 col-md-4">
    <div class="thumbnail">
        <img class ="imgg" src="@Model.A_ImageThumbnailURL" alt="">
        <div class="caption">
            <h3>
                <a asp-controller="Artists" asp-action="Details" asp-route-id="@Model.ArtistID">@Model.A_Name</a>
            </h3>

            <p class="para">@Model.A_ShortDescription</p>
        </div>

    </div>
</div>

Views/Shared/_Carousel.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<div class="slide">
<div class="row carousel-holder">
    <div class="col-md-12">
        <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
            <ol class="carousel-indicators">
                <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                <li data-target="#carousel-example-generic" data-slide-to="1"></li>
                <li data-target="#carousel-example-generic" data-slide-to="2"></li>
            </ol>
            
            <div class="carousel-inner">
                <div class="item active">
                    <img class="slide-image" src="~/Images/Concertss_1.jpg" alt="">
                </div>
                <div class="item">
                    <img class="slide-image" src="~/Images/Restaurant_1.jpg" alt="">
                </div>
                <div class="item">
                    <img class="slide-image" src="~/Images/music.jpg" alt="">
                </div>
            </div>
                
            <div class="arrowc">
            <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
                <span class="glyphicon glyphicon-chevron-left"></span>
            </a>
            <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
                <span class="glyphicon glyphicon-chevron-right"></span>
            </a>
            </div>
        </div>
    </div>
</div>
</div>

Views/Shared/_Carousel2.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<div class="slide1">
    <div class="row carousel-holder">
        <div class="col-md-12">
            <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
                <ol class="carousel-indicators">
                    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
                    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
                </ol>

                <div class="carousel-inner">
                    <div class="item active">
                        <img class="slide-image" src="~/Images/solo-sing.png" alt="">
                    </div>
                    <div class="item">
                        <img class="slide-image" src="~/Images/pexels-tima-miroshnichenko-5805040.jpg" alt="">
                    </div>
                    <div class="item">
                        <img class="slide-image" src="~/Images/Solo-musician.jpeg" alt="">
                    </div>
                </div>
                <div class="arrowc">
                <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
                    <span class="glyphicon glyphicon-chevron-left"></span>
                </a>
                <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
                    <span class="glyphicon glyphicon-chevron-right"></span>
                </a>
                </div>
            </div>
        </div>
    </div>
</div>

Views/Shared/_EventCard.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@model Events
    
<div class="col-sm-4 col-lg-    4 col-md-4">
    <div class="thumbnail">
        <img src="@Model.ImageThumbnailURL" alt="">
        <div class="caption">
            <h3>
                <a asp-controller="Events" asp-action="Details" asp-route-id="@Model.Eventid">@Model.Name</a>
            </h3>

            <p class="para">@Model.ShortDescription</p>
        </div>
       
    </div>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro">
    <link href="~/lib/bootstrap/css/bootstrap.css" rel="stylesheet" />
    <script src="~/lib/jquery/jquery.js"></script>
    <script src="~/lib/bootstrap/js/bootstrap.js"></script>
    <link href="~/Content/Style.css" rel="stylesheet" />
</head>
<body>
    <div class="container">

        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        
                    </button>
                </div>
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

                    @*<p class="lead">
        <img class="img-responsive" alt="Riyadh Voice logo" src="~/Images/riyad_logo.png"/>
        </p>*@

                    <div class="row">
                        <div class="col-md-3">
                            <p class="lead">
                                <img class="img-responsive" alt="Bethany's Pie Shop'" src="~/Images/riyadh-logo-retina-min.png" />
                            </p>
                        </div>
                        <ul class="nav navbar-nav">

                            <li><a asp-controller="Home" asp-action="Index">Home</a></li>
                            <li><a asp-controller="Vision" asp-action="Index">Vision</a></li>
                            <li><a asp-controller="Artists" asp-action="List">Artist Management</a></li>
                            <li><a asp-controller="Events" asp-action="List">Events</a></li>
                            <li><a asp-controller="Contact" asp-action="Index">Contact us</a></li>

                        </ul>



                    </div>
                </div>
             </div>
        </nav>
        @*<div class="row">
            <div class="col-md-3">
                <p class="lead">
                    <img class="img-responsive" alt="Bethany's Pie Shop'" src="~/Images/riyadh-logo-retina-min.png" />
                </p>
            </div>*@
            <div>
                <br />
            </div>
            <div>
                <br />
            </div>
        </div>
        
        <div>
            <br />
        </div>
        <div>
            <br />
        </div>

        <div>
            <br />
        </div>
        <div>
            <br />
        </div>

        


        <div class="col-md-9">
            @RenderBody()
        </div>
    
       

</body>
</html>

Views/Vision/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}


<div class="welcomeText">

<h3>Our Vision</h3>
    <p>
        Our Vision is to provide inner piece to your soul with our music and leave no corner for stress beneath you.
    </p>

    <br>
    <br />

    <br />
    <br />
   
    <h3>Our mission</h3>
    <p>
        We take pride in our work, therefore, with our years of experienced and qualified staff, excellent coordination and planning skills, we guarantee you 100% satisfaction when you allow us to take charge of every detail. We hope to be able to service you, when we do, we will make sure that in that special day you and your guests can enjoy a grand event leaving with nothing to do except enjoy yourself.we'll take care of the rest.
    </p>
    </div>